In [1]:
import pandas as pd
from dateutil import parser
import time

In [2]:
df2017 = pd.read_csv('/Volumes/TRANSCEND/Violence Tracker/Kansas City, MO/Kansas_City_KCPD_Crime_Data_2017.csv')
df2016 = pd.read_csv('/Volumes/TRANSCEND/Violence Tracker/Kansas City, MO/Kansas_City_KCPD_Crime_Data_2016.csv')
df2015 = pd.read_csv('/Volumes/TRANSCEND/Violence Tracker/Kansas City, MO/Kansas_City_KCPD_Crime_Data_2015.csv')
df2014 = pd.read_csv('/Volumes/TRANSCEND/Violence Tracker/Kansas City, MO/Kansas_City_KCPD_Crime_Data_2014.csv')

In [20]:
#dataset for different year have different format/column names
#year 2017 and year 2014 don't have separate long/lat variable, but may contain in the Location 1 variable
df2014.shape

(124832, 24)

In [4]:
df2015.shape

(121901, 26)

In [5]:
df2016.shape

(127877, 26)

In [6]:
df2017.shape

(66768, 24)

In [7]:
df2017.columns

Index(['Report_No', 'Reported_Date', 'Reported_Time', 'From_Date', 'From_Time',
       'To_Date', 'To_Time', 'Offense', 'IBRS', 'Description', 'Beat',
       'Address', 'City', 'Zip Code', 'Rep_Dist', 'Area', 'DVFlag', 'Invl_No',
       'Involvement', 'Race', 'Sex', 'Age', 'Firearm Used Flag', 'Location 1'],
      dtype='object')

In [8]:
df2016.columns

Index(['Report_No', 'Reported_Date', 'Reported_Time', 'From_Date', 'From_Time',
       'To_Date', 'To_Time', 'Offense', 'IBRS', 'Description', 'Beat',
       'Address', 'City', 'Zip Code', 'Rep_Dist', 'Area', 'DVFlag', 'Invl_No',
       'Involvement', 'Race', 'Sex', 'Age', 'Firearm Used Flag', 'Latitude',
       'Longitude', 'Location 1'],
      dtype='object')

In [9]:
df2015.columns

Index(['Report_No', 'Reported_Date', 'Reported Time', 'From_Date', 'From Time',
       'To_Date', 'To Time', 'Offense', 'IBRS', 'Description', 'Beat',
       'Address', 'City', 'Zip Code', 'Rep_Dist', 'Area', 'DVFlag', 'Invl_No',
       'Involvement', 'Race', 'Sex', 'Age', 'Firearm Used Flag', 'Latitude',
       'Longitude', 'Location 1'],
      dtype='object')

In [10]:
df2014.columns

Index(['Report_No', 'Reported_Date', 'Reported Time', 'From_Date', 'From Time',
       'To_Date', 'To Time', 'Offense', 'IBRS', 'Description', 'Beat',
       'Address', 'City', 'Zip Code', 'Rep_Dist', 'Area', 'DVFlag', 'Invl_No',
       'Involvement', 'Race', 'Sex', 'Age', 'Location 1',
       'Firearm Used Flag  '],
      dtype='object')

In [13]:
df2017.head().T

,0,1,2,3,4
Report_No,170024243,170012659,170017716,170003162,170024530
Reported_Date,04/05/2017,02/20/2017,03/11/2017,01/13/2017,04/06/2017
Reported_Time,14:53,06:59,20:16,13:55,16:45
From_Date,04/05/2017,02/20/2017,03/10/2017,01/12/2017,04/06/2017
From_Time,11:30,05:15,22:30,16:00,16:05
To_Date,04/05/2017,02/20/2017,03/11/2017,01/13/2017,04/06/2017
To_Time,14:00,05:44,17:15,13:45,16:10
Offense,501,1401,401,501,630
IBRS,220,290,13A,220,23C
Description,Burglary - Residence,Property Damage,Aggravated Assault (,Burglary - Residence,Stealing Shoplifting
Beat,535,133,331,113,411
Address,700 E 139 ST,4000 BALTIMORE AV,3200 E 27 ST,1900 MAIN ST,200 NE ENGLEWOOD RD
City,KANSAS CITY,KANSAS CITY,KANSAS CITY,KANSAS CITY,KANSAS CITY
Zip Code,64145,64111,64127,64108,64118
Rep_Dist,PJ7415,PJ3283,PJ2247,PJ1617,PC0724
Area,SPD,CPD,EPD,CPD,NPD
DVFlag,U,U,N,U,U
Invl_No,1,1,2,1,1
Involvement,VIC,SUS,VIC,VIC,VIC
Race,NaN,U,W,W,NaN
Sex,NaN,U,M,M,NaN
Age,NaN,NaN,28,NaN,NaN
Firearm Used Flag,N,N,Y,N,N
Location 1,700 E 139 ST\nKANSAS CITY 64145\n,4000 BALTIMORE AV\nKANSAS CITY 64111\n(39.0539...,"3200 E 27 ST\nKANSAS CITY 64127\n(39.076866, -...","1900 MAIN ST\nKANSAS CITY 64108\n(39.090153, -...",200 NE ENGLEWOOD RD\nKANSAS CITY 64118\n(39.19...

In [19]:
print(df2017.iloc[6]['Location 1'])

6000 CHERRY ST
KANSAS CITY 64110
(39.018377, -94.581237)

In [21]:
frames = [df2014,df2015,df2016,df2017]
df = pd.concat(frames);df.head()

,Address,Age,Area,Beat,City,DVFlag,Description,Firearm Used Flag,Firearm Used Flag,From Time,...,Rep_Dist,Report_No,Reported Time,Reported_Date,Reported_Time,Sex,To Time,To_Date,To_Time,Zip Code
0,7800 E 102 ST,NaN,SPD,542,KANSAS CITY,U,Burglary - Residence,NaN,N,14:56,...,PJ6742,140006486,14:56,01/28/2014 12:00:00 AM,NaN,F,NaN,NaN,NaN,64134.0
1,3400 N CHELSEA AV,NaN,SCP,632,KANSAS CITY,N,Stealing From Auto,NaN,N,10:00,...,PC1385,140051046,19:26,07/21/2014 12:00:00 AM,NaN,M,23:00,07/17/2014 12:00:00 AM,NaN,64117.0
2,6000 PARK AV,NaN,MPD,224,KANSAS CITY,U,Armed Robbery,NaN,Y,20:50,...,PJ4870,140085128,20:57,11/25/2014 12:00:00 AM,NaN,F,NaN,NaN,NaN,64130.0
3,2700 PEERY AV,NaN,EPD,321,KANSAS CITY,U,Dead Body,NaN,N,8:00,...,PJ1043,140050632,8:22,07/20/2014 12:00:00 AM,NaN,F,8:15,07/20/2014 12:00:00 AM,NaN,64127.0
4,9400 WHITE AV,NaN,SPD,541,KANSAS CITY,U,Aggravated Assault (,NaN,N,0:01,...,PJ6478,140086872,18:49,12/03/2014 12:00:00 AM,NaN,M,23:59,11/19/2014 12:00:00 AM,NaN,64138.0

In [23]:
df.columns

Index(['Address', 'Age', 'Area', 'Beat', 'City', 'DVFlag', 'Description',
       'Firearm Used Flag', 'Firearm Used Flag  ', 'From Time', 'From_Date',
       'From_Time', 'IBRS', 'Invl_No', 'Involvement', 'Latitude', 'Location 1',
       'Longitude', 'Offense', 'Race', 'Rep_Dist', 'Report_No',
       'Reported Time', 'Reported_Date', 'Reported_Time', 'Sex', 'To Time',
       'To_Date', 'To_Time', 'Zip Code'],
      dtype='object')

In [26]:
df['Reported_Date']=df['Reported_Date'].apply(parser.parse);

In [28]:
df['year'], df['month'] = df['Reported_Date'].dt.year, df['Reported_Date'].dt.month
df.head()

,Address,Age,Area,Beat,City,DVFlag,Description,Firearm Used Flag,Firearm Used Flag,From Time,...,Reported Time,Reported_Date,Reported_Time,Sex,To Time,To_Date,To_Time,Zip Code,year,month
0,7800 E 102 ST,NaN,SPD,542,KANSAS CITY,U,Burglary - Residence,NaN,N,14:56,...,14:56,2014-01-28,NaN,F,NaN,NaN,NaN,64134.0,2014,1
1,3400 N CHELSEA AV,NaN,SCP,632,KANSAS CITY,N,Stealing From Auto,NaN,N,10:00,...,19:26,2014-07-21,NaN,M,23:00,07/17/2014 12:00:00 AM,NaN,64117.0,2014,7
2,6000 PARK AV,NaN,MPD,224,KANSAS CITY,U,Armed Robbery,NaN,Y,20:50,...,20:57,2014-11-25,NaN,F,NaN,NaN,NaN,64130.0,2014,11
3,2700 PEERY AV,NaN,EPD,321,KANSAS CITY,U,Dead Body,NaN,N,8:00,...,8:22,2014-07-20,NaN,F,8:15,07/20/2014 12:00:00 AM,NaN,64127.0,2014,7
4,9400 WHITE AV,NaN,SPD,541,KANSAS CITY,U,Aggravated Assault (,NaN,N,0:01,...,18:49,2014-12-03,NaN,M,23:59,11/19/2014 12:00:00 AM,NaN,64138.0,2014,12

In [31]:
df['Description'].unique()

array(['Burglary - Residence', 'Stealing From Auto', 'Armed Robbery',
       'Dead Body', 'Aggravated Assault (', 'Misc Violation',
       'Stealing Auto Parts/', 'Agg Assault - Domest',
       'Strong Arm Robbery', 'Resisting an Officer', 'Family Offense',
       'Non Agg Assault Dome', 'Non Aggravated Assau',
       'Agg Assault - Drive-', 'Possession/Sale/Dist', 'Property Damage',
       'Auto Theft', 'Possession of Drug E', 'Kidnapping/Abduction',
       'Stealing Purse Snatc', 'Intimidation', 'Stealing from Buildi',
       'Stealing All Other', 'Rape', 'Arson', 'Weapons Law Violatio',
       'Driving Under Influe', 'Violation Full Order',
       'Negligent Manslaught', 'Sex Offense -others',
       'Sex Off Fondle - mol', 'Forcible Sodomy', 'Disorderly Conduct',
       'Child Endangerment', 'Forcible Fondling', 'Animal Bite - Dog',
       'Sex Off Indecent Exp', 'Interference with Cu',
       'Sex Off Misconduct', 'HOMICIDE/Non Neglige', 'Stealing Pickpocket',
       'Statutory Rape', 'child pornography', 'Pornography',
       'Hit and Run of a Per', 'Family Disturbance',
       'Sex Off Indecent Con', 'Sex Off Follow/Entic',
       'Stealing Shoplifting', 'Liquor Law Violaton',
       'Casualty (includes a', 'Attempt Suicide by H', 'Trespassing',
       'Stealing Bicycles', 'Attempt Suicide by C', 'Burglary - Non Resid',
       'Arson with Fire Bomb', 'Attempt Suicide by O',
       'Attempt Suicide by S', 'Impersonation', 'Suicide by Other Mea',
       'Attempt Suicide by P', 'Suicide By Sleeping',
       'Auto Theft Outside S', 'Stolen Property OFFE', 'Forgery',
       'Fraud/Confidence Gam', 'Curfew', 'Credit/Debit/ATM Car',
       'Embezzlement', 'Counterfeiting', 'Impersonation - NOT',
       'False Information to', 'Prostitution/Patroni', 'Forged Checks',
       'stealing from bldg', 'Violation Ex Parte O', 'False ID',
       'Sex Off Incest', 'Attempt Suicide by J', 'sex offense -others',
       'Bomb Threat/Intimida', 'Wire Fraud', 'Drunkenness',
       'Fraud Confidence Gam', 'Failure to Return', 'Stalking',
       'Stealing Coin Operat', 'armed robbery', 'Peeping Tom',
       'Promoting Prostituti', 'Passing Bad Checks', 'Suicide By Shooting',
       'Justifiable Homicide', 'Loitering', 'Suicide By Hanging',
       'Aggravated Assault', 'Non Agg Assault', 'misc investigation',
       'Agg Assault Dome', ']', 'Bombing (other than',
       'Resisting an officer', 'PROPERY DAMAGE', 'AGG DV ASSAULT',
       'Sexual Assault with', 'Misc Investigation', 'Harassment',
       'aggravated assault', 'PROPERTY DAMAGE', 'Extortion/Blackmail',
       'AUTO THEFT', 'Walking in Street', 'interuption of servi',
       'liquor law violation', 'intimidation', 'counterfieting', 'fraud',
       'property damage', 'CHILD ABUSE', 'Missing/Runaway Juve',
       'Arson OTH', 'prowling', 'Prostitution/Solicit', 'Identity Theft',
       '403', 'Welfare Fraud', 'RAPE', 'misc juv', 'Animal Bite - All Ot',
       'auto theft', 'Hindering', 'impersonation', 'Auto Theft7', 'resist',
       'Gambling - Operating', 'Fraud', 'STEALING ACC',
       'Intimidation (DV)', 'embezzlement', 'Counterfeitting',
       'Receiving Stolen Pro', 'burglary', 'Stealig All Other',
       'PROPERTY DAM', 'Agg Assault', 'Suicide By Cutting', 'STEALING',
       'possession of drug e', 'resisting officer', '1',
       'Hacking/Computer Inv', 'NON AGG ASSAULT DV',
       'Attempt Suicide by G', 'non agg assault', 'forgery',
       'Idenity Theft', 'INTIMIDATE', 'Animal Cruelty', 'Burg Res Occ',
       'disorderly conduct', 'agg dv assault', 'misc off', 'kidnapping',
       'Suicide - Domestic V', 'STEAL TFA', 'trespassing', '4',
       'Misc Viol(2601)', 'Vagrancy', 'Human Trafficking/Co'], dtype=object)

In [32]:
df = df[(df['Description'] == 'Justifiable Homicide') | (df['Description'] == 'HOMICIDE/Non Neglige')]

In [38]:
df_count = df.groupby(['year','month','Description']).size().reset_index(name='count')

In [39]:
df_count=df_count.rename(columns = {'Description':'homicide_type'});df_count.head()

   year  month         homicide_type  count
0  2014      1  HOMICIDE/Non Neglige     15
1  2014      2  HOMICIDE/Non Neglige      2
2  2014      3  HOMICIDE/Non Neglige      8
3  2014      4  HOMICIDE/Non Neglige     13
4  2014      5  HOMICIDE/Non Neglige     10

In [40]:
df_count.insert(0,'City','Kansas')
df_count.insert(1,'State','MO')
df_count['UCR_Type'] = ''
df_count.head(15)

      City State  year  month         homicide_type  count UCR_Type
0   Kansas    MO  2014      1  HOMICIDE/Non Neglige     15
1   Kansas    MO  2014      2  HOMICIDE/Non Neglige      2
2   Kansas    MO  2014      3  HOMICIDE/Non Neglige      8
3   Kansas    MO  2014      4  HOMICIDE/Non Neglige     13
4   Kansas    MO  2014      5  HOMICIDE/Non Neglige     10
5   Kansas    MO  2014      6  HOMICIDE/Non Neglige     10
6   Kansas    MO  2014      7  HOMICIDE/Non Neglige     16
7   Kansas    MO  2014      8  HOMICIDE/Non Neglige     17
8   Kansas    MO  2014      8  Justifiable Homicide      3
9   Kansas    MO  2014      9  HOMICIDE/Non Neglige     26
10  Kansas    MO  2014     10  HOMICIDE/Non Neglige     12
11  Kansas    MO  2014     11  HOMICIDE/Non Neglige     10
12  Kansas    MO  2014     12  HOMICIDE/Non Neglige     14
13  Kansas    MO  2015      1  HOMICIDE/Non Neglige     26
14  Kansas    MO  2015      2  HOMICIDE/Non Neglige      6

Strange enough, homicides counts has a huge gap compared to their officially homicide report (in pdf version)

In [47]:
sum(df_count[df_count['year'] == 2016]['count'])

254

In [51]:
df_count.to_csv('Kansas_MO_Homicide_Data_counts.csv',index=False,encoding='utf-8')