** Note that NYC's homicide counts are constantly smaller than UCR report.** 

** Also, since we have two separate dataset, one is for 2005-2016 and one is for first queater in 2017, we have count incidents in 2017 (reported in 2017 but happened in 2016, and then add those numbers to 2016's counting.**

In [108]:
import pandas as pd
from dateutil import parser

In [109]:
nyc = pd.read_csv('/Volumes/TRANSCEND/Violence Tracker/NYC/NYPD_Crimes_2006-2015.csv')

//anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [110]:
nyc.dtypes

CMPLNT_NUM             int64
CMPLNT_FR_DT          object
CMPLNT_FR_TM          object
CMPLNT_TO_DT          object
CMPLNT_TO_TM          object
RPT_DT                object
KY_CD                  int64
OFNS_DESC             object
PD_CD                float64
PD_DESC               object
CRM_ATPT_CPTD_CD      object
LAW_CAT_CD            object
JURIS_DESC            object
BORO_NM               object
ADDR_PCT_CD          float64
LOC_OF_OCCUR_DESC     object
PREM_TYP_DESC         object
PARKS_NM              object
HADEVELOPT            object
X_COORD_CD           float64
Y_COORD_CD           float64
Latitude             float64
Longitude            float64
Lat_Lon               object
dtype: object

In [111]:
nyc.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,101109527,12/31/2015,23:45:00,NaN,NaN,12/31/2015,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",...,44.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,1007314.0,241257.0,40.828848,-73.916661,"(40.828848333, -73.916661142)"
1,153401121,12/31/2015,23:36:00,NaN,NaN,12/31/2015,101,MURDER & NON-NEGL. MANSLAUGHTER,NaN,NaN,...,103.0,OUTSIDE,NaN,NaN,NaN,1043991.0,193406.0,40.697338,-73.784557,"(40.697338138, -73.784556739)"
2,569369778,12/31/2015,23:30:00,NaN,NaN,12/31/2015,117,DANGEROUS DRUGS,503.0,"CONTROLLED SUBSTANCE,INTENT TO",...,28.0,NaN,OTHER,NaN,NaN,999463.0,231690.0,40.802607,-73.945052,"(40.802606608, -73.945051911)"
3,968417082,12/31/2015,23:30:00,NaN,NaN,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,105.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1060183.0,177862.0,40.654549,-73.726339,"(40.654549444, -73.726338791)"
4,641637920,12/31/2015,23:25:00,12/31/2015,23:30:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,13.0,FRONT OF,OTHER,NaN,NaN,987606.0,208148.0,40.738002,-73.987891,"(40.7380024, -73.98789129)"

In [112]:
'''
Note: it's gonna take a while to convert string to datetime for this 'large' dataframe, around 15min
'''
nyc['CMPLNT_FR_DT'] = pd.to_datetime(nyc['CMPLNT_FR_DT'],errors='coerce')

In [114]:
nyc.CMPLNT_FR_DT.dt.year.unique()

array([ 2015.,  2013.,  2009.,  2014.,  2011.,  2004.,  2012.,  1992.,
        1969.,  2010.,  1979.,  2008.,  2006.,  2007.,  2005.,  2001.,
        1982.,    nan,  1995.,  1993.,  1965.,  2000.,  2002.,  1990.,
        1999.,  1996.,  2003.,  1987.,  1975.,  1989.,  1915.,  1986.,
        1981.,  1950.,  1998.,  1978.,  1997.,  1910.,  1991.,  1955.,
        1914.,  1958.,  1994.,  1974.,  1977.,  1980.,  1930.,  1988.,
        1913.,  1941.,  1945.,  1954.,  1971.,  1973.,  1985.,  1912.,
        1972.,  1984.,  1942.,  1983.,  1920.,  1968.,  1938.,  1911.,
        1970.,  1959.,  1909.,  1960.,  1940.,  1900.,  1929.,  1976.,
        1919.,  1908.,  1948.,  1967.,  1962.,  1966.,  1956.,  1922.,
        1906.,  1946.,  1961.,  1905.,  1964.,  2016.,  1916.])

In [115]:
nyc['Year'], nyc['Month'] = nyc['CMPLNT_FR_DT'].dt.year, nyc['CMPLNT_FR_DT'].dt.month

In [116]:
'''
NYC's data from year 2014-2016
'''
nyc_14_16 = nyc[nyc['Year'] >= 2014]

In [117]:
nyc.OFNS_DESC.unique()

array(['FORGERY', 'MURDER & NON-NEGL. MANSLAUGHTER', 'DANGEROUS DRUGS',
       'ASSAULT 3 & RELATED OFFENSES', 'FELONY ASSAULT',
       'DANGEROUS WEAPONS', 'PETIT LARCENY', 'GRAND LARCENY', 'ROBBERY',
       'OFFENSES AGAINST PUBLIC ADMINI', 'CRIMINAL MISCHIEF & RELATED OF',
       'RAPE', 'INTOXICATED & IMPAIRED DRIVING', 'HARRASSMENT 2',
       'SEX CRIMES', 'BURGLARY', 'CRIMINAL TRESPASS',
       'MISCELLANEOUS PENAL LAW', 'VEHICLE AND TRAFFIC LAWS',
       'OFF. AGNST PUB ORD SENSBLTY &', 'FRAUDS',
       'GRAND LARCENY OF MOTOR VEHICLE', 'OFFENSES INVOLVING FRAUD',
       'OFFENSES AGAINST THE PERSON', 'FRAUDULENT ACCOSTING',
       'OTHER OFFENSES RELATED TO THEF', 'GAMBLING', 'ARSON',
       'POSSESSION OF STOLEN PROPERTY', 'UNAUTHORIZED USE OF A VEHICLE',
       'THEFT-FRAUD', 'DISORDERLY CONDUCT', nan, 'ADMINISTRATIVE CODE',
       'CHILD ABANDONMENT/NON SUPPORT', 'OTHER STATE LAWS (NON PENAL LA',
       'NYS LAWS-UNCLASSIFIED FELONY', "BURGLAR'S TOOLS",
       'THEFT OF SERVICES', 'PETIT LARCENY OF MOTOR VEHICLE',
       'ALCOHOLIC BEVERAGE CONTROL LAW',
       'AGRICULTURE & MRKTS LAW-UNCLASSIFIED', 'ENDAN WELFARE INCOMP',
       'KIDNAPPING & RELATED OFFENSES', 'DISRUPTION OF A RELIGIOUS SERV',
       'PROSTITUTION & RELATED OFFENSES', 'JOSTLING',
       'ANTICIPATORY OFFENSES', 'NYS LAWS-UNCLASSIFIED VIOLATION',
       'HOMICIDE-NEGLIGENT-VEHICLE', 'OFFENSES AGAINST PUBLIC SAFETY',
       'OTHER STATE LAWS', 'ESCAPE 3', 'OFFENSES RELATED TO CHILDREN',
       'UNLAWFUL POSS. WEAP. ON SCHOOL', 'ADMINISTRATIVE CODES',
       'NEW YORK CITY HEALTH CODE', 'LOITERING/GAMBLING (CARDS, DIC',
       'ABORTION', 'KIDNAPPING AND RELATED OFFENSES', 'LOITERING',
       'OTHER STATE LAWS (NON PENAL LAW)', 'INTOXICATED/IMPAIRED DRIVING',
       'FORTUNE TELLING', 'KIDNAPPING', 'UNDER THE INFLUENCE OF DRUGS',
       'OTHER TRAFFIC INFRACTION', 'HOMICIDE-NEGLIGENT,UNCLASSIFIE',
       'LOITERING FOR DRUG PURPOSES', 'OFFENSES AGAINST MARRIAGE UNCL',
       'LOITERING/DEVIATE SEX'], dtype=object)

In [118]:
'''
Here we only count 'MURDER & NON-NEGL. MANSLAUGHTER' type 
Neg-Vehicle and HOMICIDE-NEGLIGENT does not included.
'''
#murder = ['MURDER & NON-NEGL. MANSLAUGHTER', 'HOMICIDE-NEGLIGENT-VEHICLE','HOMICIDE-NEGLIGENT,UNCLASSIFIE']
murder = ['MURDER & NON-NEGL. MANSLAUGHTER']
flag = nyc_14_16.OFNS_DESC.isin(murder)
nyc_count = nyc_14_16[flag].groupby(['Year','Month','OFNS_DESC']).size().reset_index(name='count')

In [119]:
nyc_count.insert(0,'City','New York City')
nyc_count.insert(1,'State','NY')
nyc_count['UCR_Type'] = ''
nyc_count = nyc_count.rename(columns = {'OFNS_DESC':'homicide_type'})

Note that in 2017's dataset, there might be situations that crime report date is in 2017 but occurred date is in 2016, thus we need to add those number from 17's dataset.

In [120]:
'''
Additional homicides counts from 2017's dataset (occurred in 2016 but reported in 2017) 
'''
addition_homi_for_16 = pd.read_csv("addition_homi_for_16.csv")

In [121]:
addition_homi_for_16

,City,State,Year,Month,homicide_type,count,UCR_Type
0,New York City,NY,2016.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,1,NaN
1,New York City,NY,2016.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,1,NaN
2,New York City,NY,2016.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,3,NaN
3,New York City,NY,2016.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,2,NaN

In [122]:
nyc_count

,City,State,Year,Month,homicide_type,count,UCR_Type
0,New York City,NY,2014.0,1.0,MURDER & NON-NEGL. MANSLAUGHTER,33,
1,New York City,NY,2014.0,2.0,MURDER & NON-NEGL. MANSLAUGHTER,12,
2,New York City,NY,2014.0,3.0,MURDER & NON-NEGL. MANSLAUGHTER,25,
3,New York City,NY,2014.0,4.0,MURDER & NON-NEGL. MANSLAUGHTER,20,
4,New York City,NY,2014.0,5.0,MURDER & NON-NEGL. MANSLAUGHTER,21,
5,New York City,NY,2014.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,36,
6,New York City,NY,2014.0,7.0,MURDER & NON-NEGL. MANSLAUGHTER,29,
7,New York City,NY,2014.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,32,
8,New York City,NY,2014.0,9.0,MURDER & NON-NEGL. MANSLAUGHTER,32,
9,New York City,NY,2014.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,33,
10,New York City,NY,2014.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,25,
11,New York City,NY,2014.0,12.0,MURDER & NON-NEGL. MANSLAUGHTER,33,
12,New York City,NY,2015.0,1.0,MURDER & NON-NEGL. MANSLAUGHTER,38,
13,New York City,NY,2015.0,2.0,MURDER & NON-NEGL. MANSLAUGHTER,16,
14,New York City,NY,2015.0,3.0,MURDER & NON-NEGL. MANSLAUGHTER,25,
15,New York City,NY,2015.0,4.0,MURDER & NON-NEGL. MANSLAUGHTER,24,
16,New York City,NY,2015.0,5.0,MURDER & NON-NEGL. MANSLAUGHTER,36,
17,New York City,NY,2015.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,23,
18,New York City,NY,2015.0,7.0,MURDER & NON-NEGL. MANSLAUGHTER,33,
19,New York City,NY,2015.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,37,
20,New York City,NY,2015.0,9.0,MURDER & NON-NEGL. MANSLAUGHTER,34,
21,New York City,NY,2015.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,32,
22,New York City,NY,2015.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,22,
23,New York City,NY,2015.0,12.0,MURDER & NON-NEGL. MANSLAUGHTER,24,
24,New York City,NY,2016.0,1.0,MURDER & NON-NEGL. MANSLAUGHTER,22,
25,New York City,NY,2016.0,2.0,MURDER & NON-NEGL. MANSLAUGHTER,16,
26,New York City,NY,2016.0,3.0,MURDER & NON-NEGL. MANSLAUGHTER,25,
27,New York City,NY,2016.0,4.0,MURDER & NON-NEGL. MANSLAUGHTER,26,
28,New York City,NY,2016.0,5.0,MURDER & NON-NEGL. MANSLAUGHTER,31,
29,New York City,NY,2016.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,32,
30,New York City,NY,2016.0,7.0,MURDER & NON-NEGL. MANSLAUGHTER,30,
31,New York City,NY,2016.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,35,
32,New York City,NY,2016.0,9.0,MURDER & NON-NEGL. MANSLAUGHTER,34,
33,New York City,NY,2016.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,20,
34,New York City,NY,2016.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,21,
35,New York City,NY,2016.0,12.0,MURDER & NON-NEGL. MANSLAUGHTER,22,

In [132]:
'''
Add homicide incidents which recorded in 2017's dataset
'''
nyc_count = pd.concat([nyc_count,addition_homi_for_16]).\
groupby(['City','State','Year','Month','homicide_type']).sum().reset_index()

In [135]:
nyc_14_count = nyc_count[nyc_count.Year==2014]['count'].sum()
nyc_15_count = nyc_count[nyc_count.Year==2015]['count'].sum()
nyc_16_count = nyc_count[nyc_count.Year==2016]['count'].sum()

print('Year 2014 homicide count',nyc_14_count )
print('Year 2015 homicide count',nyc_15_count )
print('Year 2016 homicide count',nyc_16_count )

Year 2014 homicide count 331
Year 2015 homicide count 344
Year 2016 homicide count 321

Note that the result is constantly smaller than the offical UCR report for year 2014 and year 2015. UCR has homicide count **333** for 2014 and **352** for 2015. Please refer to NYPD's official published report checking for consistency. 

[NYPD Report link](http://www1.nyc.gov/assets/nypd/downloads/pdf/analysis_and_planning/seven-major-felony-offenses-2000-2016.pdf)

In [136]:
nyc_count

,City,State,Year,Month,homicide_type,count,UCR_Type
0,New York City,NY,2014.0,1.0,MURDER & NON-NEGL. MANSLAUGHTER,33,NaN
1,New York City,NY,2014.0,2.0,MURDER & NON-NEGL. MANSLAUGHTER,12,NaN
2,New York City,NY,2014.0,3.0,MURDER & NON-NEGL. MANSLAUGHTER,25,NaN
3,New York City,NY,2014.0,4.0,MURDER & NON-NEGL. MANSLAUGHTER,20,NaN
4,New York City,NY,2014.0,5.0,MURDER & NON-NEGL. MANSLAUGHTER,21,NaN
5,New York City,NY,2014.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,36,NaN
6,New York City,NY,2014.0,7.0,MURDER & NON-NEGL. MANSLAUGHTER,29,NaN
7,New York City,NY,2014.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,32,NaN
8,New York City,NY,2014.0,9.0,MURDER & NON-NEGL. MANSLAUGHTER,32,NaN
9,New York City,NY,2014.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,33,NaN
10,New York City,NY,2014.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,25,NaN
11,New York City,NY,2014.0,12.0,MURDER & NON-NEGL. MANSLAUGHTER,33,NaN
12,New York City,NY,2015.0,1.0,MURDER & NON-NEGL. MANSLAUGHTER,38,NaN
13,New York City,NY,2015.0,2.0,MURDER & NON-NEGL. MANSLAUGHTER,16,NaN
14,New York City,NY,2015.0,3.0,MURDER & NON-NEGL. MANSLAUGHTER,25,NaN
15,New York City,NY,2015.0,4.0,MURDER & NON-NEGL. MANSLAUGHTER,24,NaN
16,New York City,NY,2015.0,5.0,MURDER & NON-NEGL. MANSLAUGHTER,36,NaN
17,New York City,NY,2015.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,23,NaN
18,New York City,NY,2015.0,7.0,MURDER & NON-NEGL. MANSLAUGHTER,33,NaN
19,New York City,NY,2015.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,37,NaN
20,New York City,NY,2015.0,9.0,MURDER & NON-NEGL. MANSLAUGHTER,34,NaN
21,New York City,NY,2015.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,32,NaN
22,New York City,NY,2015.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,22,NaN
23,New York City,NY,2015.0,12.0,MURDER & NON-NEGL. MANSLAUGHTER,24,NaN
24,New York City,NY,2016.0,1.0,MURDER & NON-NEGL. MANSLAUGHTER,22,NaN
25,New York City,NY,2016.0,2.0,MURDER & NON-NEGL. MANSLAUGHTER,16,NaN
26,New York City,NY,2016.0,3.0,MURDER & NON-NEGL. MANSLAUGHTER,25,NaN
27,New York City,NY,2016.0,4.0,MURDER & NON-NEGL. MANSLAUGHTER,26,NaN
28,New York City,NY,2016.0,5.0,MURDER & NON-NEGL. MANSLAUGHTER,31,NaN
29,New York City,NY,2016.0,6.0,MURDER & NON-NEGL. MANSLAUGHTER,33,NaN
30,New York City,NY,2016.0,7.0,MURDER & NON-NEGL. MANSLAUGHTER,30,NaN
31,New York City,NY,2016.0,8.0,MURDER & NON-NEGL. MANSLAUGHTER,36,NaN
32,New York City,NY,2016.0,9.0,MURDER & NON-NEGL. MANSLAUGHTER,34,NaN
33,New York City,NY,2016.0,10.0,MURDER & NON-NEGL. MANSLAUGHTER,23,NaN
34,New York City,NY,2016.0,11.0,MURDER & NON-NEGL. MANSLAUGHTER,23,NaN
35,New York City,NY,2016.0,12.0,MURDER & NON-NEGL. MANSLAUGHTER,22,NaN

In [137]:
nyc_count.to_csv('NYC_NYPD_homicide_counts_2014_2016.csv',index=False,encoding='utf-8')